logging:
  level.org.springframework: INFO
  level.com.dbg: DEBUG
spring:
  datasource:
    url: jdbc:hsqldb:mem:dataSource
    username: sa
    password:
---
spring:
  profiles.active: local
  datasource:
    url: jdbc:mysql://localhost:3306/films
    username: user
    password: userpass
  jpa:
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect